server:
  port: 8090
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway-server
  cloud:
    gateway:
      routes:
      - id: globank-challenge-cliente
        uri: lb://globank-challenge-cliente
        predicates:
          - Path=/apigateway-cliente/**
        filters:
          - StripPrefix=1
      - id: globank-challenge-cuenta
        uri: lb://globank-challenge-cuenta
        predicates:
          - Path=/apigateway-cuenta/**
        filters:
          - StripPrefix=1
      - id: globank-challenge-movimiento
        uri: lb://globank-challenge-movimiento
        predicates:
          - Path=/apigateway-movimiento/**
        filters:
          - StripPrefix=1